<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net8.0-windows10.0.19041.0</TargetFrameworks>
    <AssemblyName>StreamDeckCurrentMedia</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>partial</TrimMode>
    <InvariantGlobalization>true</InvariantGlobalization>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <SuppressTrimAnalysisWarnings>true</SuppressTrimAnalysisWarnings>
    <TrimmerSingleWarn>false</TrimmerSingleWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StreamDeck-Tools" Version="6.3.2" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.4" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <Compile Remove="Providers\Windows\**" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0-windows10.0.19041.0'">
    <Compile Remove="Providers\Mac\**" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.10" />
  </ItemGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="StreamDeckTools" />
    <TrimmerRootAssembly Include="Newtonsoft.Json" />
    <TrimmerRootAssembly Include="Microsoft.CSharp" />
    <TrimmerRootAssembly Include="SixLabors.ImageSharp" />
  </ItemGroup>
</Project>
